#!/bin/bash
#
#
if [ ! -f /usr/sbin/$(basename "$0") ]; then
cp $0 /usr/sbin
fi

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color


multipath -ll 1>/tmp/multipath.ll.$$
multipath -v3 &>/tmp/multipath.v3.$$

DEVICES=$(cat /tmp/multipath.v3.$$ | awk -F"\||:"  '/\| sd/ {print $2}' |sort -u)


while IFS= read -r LINE; do

  if [ $(echo ${LINE} | grep -c "${DEVICES[*]}") -eq 0  ]; then
    echo "${LINE}"
  else
    DEVICE=$(echo "$LINE" | awk -F"[0-9]+\:[0-9]+\:[0-9]+\:[0-9]" '{print $2}'|awk '{print $1}')
    PORTAL=$(cat /tmp/multipath.v3.$$ |awk -F"\| " '{print $2}'| awk '/'$DEVICE': tgt_node_name/ {print $0}'|awk -F":" '{print $3}'|sort -u)
    if [ $(echo "${LINE}" | grep -c "faulty") -eq 0 ]; then
      printf "${GREEN}${LINE} ${YELLOW}($PORTAL)${NC}\n"
    else
      printf "${RED}${LINE} ${YELLOW}($PORTAL)${NC}\n"
    fi
  fi
done < /tmp/multipath.ll.$$


rm /tmp/multipath.*.$$
