#!/bin/bash
# Author: Gaetan MARAIS
# Date  : 2025/02/15
#
# This script is about helping multipath diagnose with DataCore SSY vDisks
#   it will add FrontEnd info infront of Lun targets
#   coupled with SSY RestAPI it could also add the SSY vDisk name to the Multipath
#
#############################################################
#############################################################
#  SSY Credentials are store here : /root/.SSY/credentials
#  ServerHost=xxx.xxx.xxx.xxx
#  SSYUserName=SSYreadonly
#  SSYPassword=SSYpassword
#


if [ ! -f /usr/sbin/$(basename "$0") ]; then
cp $0 /usr/sbin
fi



RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# SSY connection by RESTAPI
#

if [ -f /root/.SSY/credentials ] ; then

  if [ $(whereis jq|wc -w) -le 1 ] ; then
    printf "${RED}JQ package is mandatory to gather data from SSY, please install the package using ${YELLOW}apt install jq${NC}\n"
    VDISKS=""
  else
    SERVERHOST=$(awk -F"=" '/ServerHost/ {print $2}' /root/.SSY/credentials)
    SSYUSER=$(awk -F"=" '/SSYUserName/ {print $2}' /root/.SSY/credentials)
    SSYPWD=$(awk -F"=" '/SSYPassword/ {print $2}' /root/.SSY/credentials)
    VDISKS=$(curl -s -m 3 -k -L -H "ServerHost: ${SERVERHOST}" -u${SSYUSER}:${SSYPWD} https://${SERVERHOST}/RestService/rest.svc/1.0/virtualdisks)
    if [ $(echo $VDISKS|jq -e 'try(.ErrorsCode)') ]; then
      VDISKS=""
      printf "${RED}Unable to gather data from SSY, please review the credential file${NC}\n"
    fi
  fi
else
  VDISKS=""
fi

multipath -r
multipath -ll 1>/tmp/multipath.ll.$$
multipath -v3 &>/tmp/multipath.v3.$$


DEVICES=$(cat /tmp/multipath.v3.$$ | awk -F"\||:"  '/\| sd/ {print $2}' |sort -u)


while IFS= read -r LINE; do
  VDISK=""
  if [ $(echo ${LINE} | grep -c "${DEVICES[*]}") -eq 0  ]; then
    if [ $(echo ${LINE} | grep -c "DataCore,Virtual Disk") -eq 1 ]; then
       NAA=$(echo ${LINE} | awk -F'[()]' '{print substr($2,2)}' | tr '[:lower:]' '[:upper:]')
       if [[ $VDISKS ]] ; then VDISK=$(echo ${VDISKS}|jq --arg name $NAA -r '.[] | select(.ScsiDeviceIdString == $name) | .Alias') ; fi
    fi
    if [[ $VDISK ]] ; then printf "\n${YELLOW}[${VDISK}]${NC} ${LINE} ${YELLOW}[${VDISK}]${NC}\n"
    else
      if [ $(echo "${LINE}" | grep -c "status=active") -eq 1 ]; then GREEN='\033[1;32m'; fi
      if [ $(echo "${LINE}" | grep -c "status=enabled") -eq 1 ]; then GREEN='\033[1;34m'; fi
      echo "${LINE}"
    fi
  else
    DEVICE=$(echo "$LINE" | awk -F"[0-9]+\:[0-9]+\:[0-9]+\:[0-9]" '{print $2}'|awk '{print $1}')
    PORTAL=$(cat /tmp/multipath.v3.$$ |awk -F"\| " '{print $2}'| awk '/'$DEVICE': tgt_node_name/ {print $0}'|awk -F":" '{print $3}'|sort -u)
    if [ $(echo "${LINE}" | grep -c "faulty") -eq 0 ]; then
      printf "${GREEN}${LINE} ${YELLOW}($PORTAL)${NC}\n"
    else
      printf "${RED}${LINE} ${YELLOW}($PORTAL)${NC}\n"
    fi
  fi
done < /tmp/multipath.ll.$$


rm /tmp/multipath.*.$$
